name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls
      - name: Sample JS Action
        id: greet
        uses: ikefe/hello-world-javascript-action@main
