name: Actions Workflow
# passing as an objects

on:
  push:
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -al
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          # git clone git@github:$GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA
      - name: Checkout
        uses: actions/checkout@v3
      - name: List Files After Checkout
        run: |
          pwd
          ls -al
      - name: Sample JS Action
        id: greet
        uses: ikefe/hello-world-javascript-action@main
        with:
          who-to-greet: Innocent
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
